# Generated by Django 2.2 on 2019-05-01 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=3, null=True)),
                ('phone', models.IntegerField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Registration',
                'db_table': 'user_registration',
            },
        ),
    ]
