# Generated by Django 2.2 on 2019-05-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_createevent_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createevent',
            old_name='time',
            new_name='time1',
        ),
    ]
