# Generated by Django 2.2 on 2019-05-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20190503_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='time1',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
