# Generated by Django 2.2 on 2019-05-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20190506_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='time1',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
