# Generated by Django 2.2 on 2019-05-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_auto_20190506_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='registered',
            field=models.CharField(default=False, max_length=500, null=True),
        ),
    ]
