# Generated by Django 2.2 on 2019-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_createevent_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='time1',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
