# Generated by Django 2.2 on 2019-05-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_auto_20190506_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='time1',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
