# Generated by Django 2.2 on 2019-05-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_auto_20190506_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='time1',
            field=models.TimeField(null=True),
        ),
    ]
