# Generated by Django 2.2 on 2019-05-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0016_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createevent',
            name='registered',
        ),
        migrations.AddField(
            model_name='participate',
            name='registered',
            field=models.CharField(default='False', max_length=500, null=True),
        ),
    ]
